create_clock -name clk125M -period 8.000 -waveform {0.000 4.000} [get_ports clk125M]


set_input_delay -clock [get_clocks clk125M] -min -add_delay 2.000 [get_ports c]
set_input_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports c]
set_input_delay -clock [get_clocks clk125M] -min -add_delay 2.000 [get_ports rst]
set_input_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports rst]

set_output_delay -clock [get_clocks clk125M] -min -add_delay 4.000 [get_ports {hl[2]}]
set_output_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports {hl[2]}]
set_output_delay -clock [get_clocks clk125M] -min -add_delay 4.000 [get_ports {hl[1]}]
set_output_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports {hl[1]}]
set_output_delay -clock [get_clocks clk125M] -min -add_delay 4.000 [get_ports {hl[0]}]
set_output_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports {hl[0]}]
set_output_delay -clock [get_clocks clk125M] -min -add_delay 4.000 [get_ports {fl[2]}]
set_output_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports {fl[2]}]
set_output_delay -clock [get_clocks clk125M] -min -add_delay 4.000 [get_ports {fl[1]}]
set_output_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports {fl[1]}]
set_output_delay -clock [get_clocks clk125M] -min -add_delay 4.000 [get_ports {fl[0]}]
set_output_delay -clock [get_clocks clk125M] -max -add_delay 5.000 [get_ports {fl[0]}]

set_property PACKAGE_PIN H16 [get_ports clk125M]
set_property PACKAGE_PIN M19 [get_ports rst]
set_property PACKAGE_PIN M20 [get_ports c]
set_property PACKAGE_PIN M15 [get_ports {hl[2]}]
set_property PACKAGE_PIN G14 [get_ports {hl[1]}]
set_property PACKAGE_PIN L14 [get_ports {hl[0]}]
set_property PACKAGE_PIN N15 [get_ports {fl[2]}]
set_property PACKAGE_PIN L15 [get_ports {fl[1]}]
set_property PACKAGE_PIN G17 [get_ports {fl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports clk125M]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports {fl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {fl[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hl[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hl[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {hl[0]}]

set_property PACKAGE_PIN H16 [get_ports clk125M]
